export const MODAL_BODY_TYPES = {
    USER_DETAIL: "USER_DETAIL",
    CONFIRMATION: "CONFIRMATION",
    DEPARTMENT_ADD_NEW: "DEPARTMENT_ADD_NEW",
    DEFAULT: "",
  };
  
  export const RIGHT_DRAWER_TYPES = {
    NOTIFICATION: "NOTIFICATION",
  };
  
  export const CONFIRMATION_MODAL_CLOSE_TYPES = {
    DECREE_DELETE: "LEAD_DELETE",
    EMAIL_SEND: "EMAIL_SEND",
    DEFAULT: "",
  };
  